import pandas as pd
df=pd.read_csv("weatherPastWeekDelhi")
pd.set_option("display.max_columns", None)
df_dict=df.to_dict()
df_list=df["Remarks"].tolist()
#df_pd=pd.read_csv(df_list)
#print(df_list[1])
#print(type(df_list))
#print(df[df["High_Temperature_C"]==df["High_Temperature_C"].max() ])
squarel_pd=pd.read_csv("2018_Central_Park_Squirrel_Census_-_Squirrel_Data_20260705.csv")
fur_count=squarel_pd["Primary Fur Color"].count()
fur_count_1=(squarel_pd["Primary Fur Color"]=="Gray").count()
fur_count_2=(squarel_pd["Primary Fur Color"]=="Cinnamon").count()
fur_count_3=(squarel_pd["Primary Fur Color"]=="Black").count()
print(fur_count_1,fur_count_2,fur_count_3)