import pandas as pd
# df=pd.read_csv("weatherPastWeekDelhi")
# pd.set_option("display.max_columns", None)
# df_dict=df.to_dict()
# df_list=df["Remarks"].tolist()
#df_pd=pd.read_csv(df_list)
#print(df_list[1])
#print(type(df_list))
#print(df[df["High_Temperature_C"]==df["High_Temperature_C"].max() ])
squarel_pd=pd.read_csv("2018_Central_Park_Squirrel_Census_-_Squirrel_Data_20260705.csv")
fur_count=squarel_pd["Primary Fur Color"].sum()
fur_count_1=(squarel_pd["Primary Fur Color"]=="Gray").sum()
fur_count_2=(squarel_pd["Primary Fur Color"]=="Cinnamon").sum()
fur_count_3=(squarel_pd["Primary Fur Color"]=="Black").sum()
print(fur_count_1, fur_count_2, fur_count_3)
# check_Grey=len(squarel_pd[squarel_pd["Primary Fur Color"]=="Gray"])
# print(check_Grey)
fur_dataFrame= pd.DataFrame({ "Fur color": ["gray", "cinnamon", "black"],
                 "fur color count": [fur_count_1, fur_count_2, fur_count_3],})
print(fur_dataFrame)
fur_dataFrame_csv=fur_dataFrame.to_csv("fur_dataFrame_toCSV", index=False)
print(fur_dataFrame_csv)